//Sunchi Wang
//Rocket Patrol Mod with a Boss
//9 hours
//modification list:
//a high score across all scenes
//my own copy right free music generated by suno AI
//a new spaceship type that's smaller, moves faster, and is worth more points
//particle explosion when the player collides with the spaceships
//remaining time is displayed in the corner
//alternating two player mode
//new timing/scoring mechanism that adds time to the clock for successful hits
//a boss that moves left and right and takes multiple hits to defeat
//a gradual increase of how fast the time ticks down


let config = {
    type: Phaser.AUTO,
    width: 640,
    height: 480,
    scene: [Menu, Play]
}

let game = new Phaser.Game(config)

// set UI sizes
let borderUISize = game.config.height / 15
let borderPadding = borderUISize / 3

// reserve keyboard bindings
let keyFIRE, keyRESET, keyLEFT, keyRIGHT, keyA, keyD, keyW, keyUP

// Add a global variable for the high score
let highScore = 0;